name: aegnn_general
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.3.1
  - numpy=1.24.2
  - pip=23.0.1
  - python=3.8.0
  - pytorch=1.11.0 #=py3.8_cuda11.3_cudnn8_0
  - torchaudio=0.11.0=py38_cu113
  - torchvision=0.12.0=py38_cu113
  - pip:
    - matplotlib==3.5.1
    - mapcalc==0.2.2
    - pytorch-lightning==1.4.9
    - torch-cluster==1.6.1
    - torch-geometric==2.0.4
    - torch-scatter==2.1.1
    - torch-sparse==0.6.13
    - torch-spline-conv==1.2.2
    - torchmetrics==0.4.0
    - wandb==0.14.0
